### ISSUE TITLE
Unable to use Ygg provider

### ISSUE THREAD

**Issue by GhyslainBruno** [JimmyLaurent/torrent-search-api#117]
**First of all, thank you for your job !** 

I am developing an [app](https://github.com/GhyslainBruno/lazyker) that has the need to search over multiple torrent providers. 
Currently, I am making my own crawlers, but I'm thinking about using your lib which seems awesome ! 

Since a few days I'm facing a new issue with Ygg provider, and to be more accurate the issue is about CloudFlare...

### Steps to reproduce : 
```javascript
const TorrentSearchApi = require('torrent-search-api');

TorrentSearchApi.enableProvider('Yggtorrent', 'USERNAME', 'PASSWORD');

TorrentSearchApi.search('1080', 'Movies', 20)
    .then(torrents => {
        console.log(torrents);
    })
    .catch(error => {
        console.log(error);
    })
```

The error the lib returns : 
<img width="483" alt="Screenshot 2020-10-20 at 11 05 22" src="https://user-images.githubusercontent.com/22811607/96567739-71162280-12c7-11eb-9a99-8d62d79ccd95.png">

I saw you're using [cloudscraper](https://www.npmjs.com/package/cloudscraper) (and even making your own [cloudflare-scraper](https://www.npmjs.com/package/cloudflare-scraper) - great !). 

CloudFlare might have updated their security system. 

I'm making this issue in here to have somewhere where we could all think about how to solve this new challenge.

_PS: This is issue might be related to [#18](https://github.com/JimmyLaurent/cloudflare-scraper/issues/18) issue from your [cloudflare-scraper](https://www.npmjs.com/package/cloudflare-scraper) repo._ 

_PS 2: On my app, I'm using puppeteer to scrape Ygg. Since a fews days the CloudFlare keeps reloading every 5 seconds. That's how I noticed the change. I don't know if it could be useful._

**Comment by RamBoFe** [comment]
Hi,

Try to use this : [pumpflare](https://github.com/unixfox/pupflare).
This works in my project !

++

**Comment by RamBoFe** [comment]
I just tested pumflare again and it doesn't seem to work anymore ... So I tried to use the cloudflare-scraper package but it didn't work. I was having the problem described in this issue . By researching I managed to make it work. Look at the solution I have proposed in this issue. I hope this will unlock you.

**Comment by RamBoFe** [comment]
Here we go again :sweat_smile:

I finally believe I have found the origin of your problem ! Problem I actually encountered ... To be exact, this is a User Agent problem.

I develop my app under Windows and I deploy on a VPS server under Linux. Very often my app managed to scraper the YggTorrent site but as soon as I deployed on my VPS it no longer worked ... At that time, I was using [pumpflare](https://github.com/unixfox/pupflare) ... I therefore resolved to drop pumpflare to try to find something else that worked under my Linux VPS. So I turned to the solution provided by the _cloudflare-scraper_ package and I managed to make it work with the trick available in this [issue](https://github.com/JimmyLaurent/cloudflare-scraper/issues/19). Unfortunately, once deployed on my VPS, it didn't work anymore !! While digging through the code, I realized that the only thing that could change compared to Windows was the User Agent. By using the Windows User Agent for all OS, I finally managed to get my app to work under my VPS.

In conclusion, the User Agent used can block access to the YggTorrent site and one should not use any value (and it should have one). For now, one of the values of the User Agent that works every time is this :

```javascript
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'
```

Depending on the value used for the User Agent, CloudFlare can react in different ways:

- Infinite reloading of the page which inevitably leads to the famous error "Timeout on just a moment" ([#18](https://github.com/JimmyLaurent/cloudflare-scraper/issues/18))
- The page simply does not load.
- Error 503 with the page containing the mention "Please enable cookies".

There may be other behaviors as well. I only listed the behaviors that I encountered.

So @GhyslainBruno uses the value of the User Agent given above and I think that you will not encounter any more problems to scraper the YggTorrent site in your app 😃 You could use this code with puppeteer : 

```javascript
await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36');
```

Here's hoping that helps.

**Comment by johann-taberlet** [comment]
Hey there,
I'm just an hobbyist and you maybe already know that way but just to let you know that I managed to make this works.
I actually used [Puppeteer extra stealth](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth#readme) (be sure to use Puppeteer@5 because typings are completely broken after that).
I then used [x-ray-chrome](https://github.com/ssbeefeater/x-ray-chrome) as a driver for x-ray-scraper and modified it to:

- point on Puppeteer-extra and add the stealth plugin
- add a timeout of 5000ms if the cookie cf_clearance is not alive (lifetime of 30mn) to pass the ddos protection
- add a function to manage the torrent download part

Then in TorrentProvider.js, I added this driver to x-ray instead of the original one.

Because Yggtorrent is my only concern, every requests use puppeteer at the moment but it should be possible to do something cleaner and use this driver only if we need a cloudflare bypass. 

As I said I'm just an hobbyist so my code is probably ugly so I'm not going to submit a PR for this but maybe this "strategy" could be implemented by someone smarter than me :)

**Comment by johann-taberlet** [comment]
Hey,
I managed to make this work by manually installing cloudflare-scraper and then manually update its dependencies like so:

```
"dependencies": {
    "hcaptcha-solver": "^1.0.1",
    "puppeteer-extra": "^3.1.18",
    "puppeteer-extra-plugin-stealth": "^2.7.6",
    "request": "^2.88.2",
    "request-promise-native": "^1.0.9",
    "stormwall-bypass": "^1.0.1"
  },
  "devDependencies": {
    "puppeteer": "^5.2.1"
  },
```

Do not use puppeteer version > than 5.2.1 because typings are broken then.

So maybe make a PR with cloudflare-scraper as a dependency for this package and update cloudflare-scraper dependencies as well?

**Comment by GhyslainBruno** [comment]
> Here we go again 😅
> 
> I finally believe I have found the origin of your problem ! Problem I actually encountered ... To be exact, this is a User Agent problem.
> 
> I develop my app under Windows and I deploy on a VPS server under Linux. Very often my app managed to scraper the YggTorrent site but as soon as I deployed on my VPS it no longer worked ... At that time, I was using [pumpflare](https://github.com/unixfox/pupflare) ... I therefore resolved to drop pumpflare to try to find something else that worked under my Linux VPS. So I turned to the solution provided by the _cloudflare-scraper_ package and I managed to make it work with the solution available in my previous comment. Unfortunately, once deployed on my VPS, it didn't work anymore !! While digging through the code, I realized that the only thing that could change compared to Windows was the User Agent. By using the Windows User Agent for all OS, I finally managed to get my app to work under my VPS.
> 
> In conclusion, the User Agent used can block access to the YggTorrent site and you should not use just any value (and it should have one). For now, one of the values of the User Agent that works every time is this :
> 
> ```js
> 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'
> ```
> 
> Depending on the value used for the User Agent, CloudFlare can react in different ways:
> 
> * Infinite reloading of the page when using _puppeteer_ directly and leads to the famous error "Timeout on just a moment" in _cloudflare-scraper_  ([#18](https://github.com/JimmyLaurent/cloudflare-scraper/issues/18) in your PS and what your describe in PS 2)
> * The page simply does not load.
> * Error 503 with the page containing the mention "Please enable cookies".
> 
> There may be other behaviors as well. I only listed the behaviors that I encountered.
> 
> So @GhyslainBruno uses the value of the User Agent given above and I think that you will not encounter any more problems to scraper the YggTorrent site in your app 😃 You could use this code with _puppeteer_ :
> 
> ```js
> await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36');
> ```
> 
> Here's hoping that helps.

@RamBoFe unfortunately it didn't work for my case neither :-/. I still have the same issue within my app (infinite reloading)

**Comment by GhyslainBruno** [comment]
> Hey,
> I managed to make this work by manually install cloudflare-scraper and then manually update its dependencies like so:
> 
> ```
> "dependencies": {
>     "hcaptcha-solver": "^1.0.1",
>     "puppeteer-extra": "^3.1.18",
>     "puppeteer-extra-plugin-stealth": "^2.7.6",
>     "request": "^2.88.2",
>     "request-promise-native": "^1.0.9",
>     "stormwall-bypass": "^1.0.1"
>   },
>   "devDependencies": {
>     "puppeteer": "^5.2.1"
>   },
> ```
> 
> Do not use puppeteer version > than 5.2.1 because typings are broken then.
> 
> So maybe make a PR with cloudflare-scraper as a dependency for this package and update cloudflare-scraper dependencies as well?
> 
> EDIT: And Yggtorrent URL has changed for https://www4.yggtorrent.li

@johann-taberlet what do you mean you managed to make it work ? 

What did you do ? ^^ 

I tried a simple `npm install cloudflare-scraper` and then change its dependencies to those you spotted, didn't work for me

**Comment by GhyslainBruno** [comment]
@johann-taberlet thanks for your advices, I just created a new [PR](https://github.com/JimmyLaurent/torrent-search-api/pull/127) that should solve this issue. 

I'm waiting for the PR to be merged and then I'll close this issue. 

In any case @JimmyLaurent doesn't have time to do so, and if someone needs to use this asap, the [fork](https://github.com/GhyslainBruno/torrent-search-api) I made will have this fix merged asap. 

Thanks for your help guys !

**Comment by tdehaeze** [comment]
@GhyslainBruno does that still works for you? I cannot make this work. My guess is that CloudFlare updated there anti-bot system.
Thanks

**Comment by RamBoFe** [comment]
Hi @tdehaeze ,

For my part, indeed cloudflare has updated its protection. So I too was stuck with my app. So I decided to look for a viable solution and after much research I found the [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) project to bypass the new Cloudflare protection. It works perfectly except that you can't ask him to download a torrent file from YggTorrent... The project owner himself [says](https://github.com/FlareSolverr/FlareSolverr/issues/207#issuecomment-950315945) that you shouldn't use his project to download files. So, I only use it to retrieve the _user-agent_ and the _cf_clearance_ cookie and then inject it into the YggTorrent provider as described [here](https://github.com/JimmyLaurent/torrent-search-api/issues/102#issuecomment-630922681).

Of course this require a code update... Take a look at my [backend app](https://github.com/RamBoFe/torramt-api/tree/master/services) (especially the file _cloudflare.mjs_ and _ygg.mjs_) to give you an idea if you want.

Good luck ++

**Comment by tdehaeze** [comment]
Thanks a lot @RamBoFe !
Where can I MP you about some part of your code I wish to implement in my app?
Cheers

**Comment by RamBoFe** [comment]
HI,

Send your email at this temporary email : ducrucrattaxe-9501@yopmail.com. I will contact you.

**Comment by Germwalker** [comment]
Is anyone having any news about the state of this projet ? Seems to not be working anymore

**Comment by MozkaGit** [comment]
> Is anyone having any news about the state of this projet ? Seems to not be working anymore

It still works, I can download torrents on YggTorrent. But for the category I still use 'All' what can I put to filter the animes? When I use 'Animes' or 'Animations' it returns me that there are 0 results that have been found...

**Comment by 404b** [comment]
If anyone still having hCaptcha Issue try  https://github.com/noCaptchaAi/docs/blob/main/docs/en/token/hCaptcha.md which gives you hCaptcha token, no need to open browser.
